version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-board
    environment:
      MYSQL_ROOT_PASSWORD: board
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - board-network

volumes:
  mysqldata:

networks:
  board-network:
